<?php
session_start();

$jsonFile = __DIR__ . '/config.json';
$jsFile   = __DIR__ . '/config.js';
$passFile = __DIR__ . '/.admin_pass';

if (!is_file($passFile)) {
    file_put_contents($passFile, "<?php return 'lian2026';\n", LOCK_EX);
}
function adminPass() {
    $f = __DIR__ . '/.admin_pass';
    return is_file($f) ? trim((string)@include $f) : 'lian2026';
}
function loadConf() {
    $f = __DIR__ . '/config.json';
    if (is_file($f)) {
        $d = json_decode(file_get_contents($f), true);
        if (is_array($d)) return $d;
    }
    return array('default' => 'https://pan.quark.cn/s/27b2535c2450', 'targets' => array());
}
function saveConf($default, $targets) {
    $jsonFile = __DIR__ . '/config.json';
    $jsFile   = __DIR__ . '/config.js';
    $data = array('default' => $default, 'targets' => $targets);
    file_put_contents($jsonFile, json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE), LOCK_EX);
    $urls = array();
    foreach ($targets as $p => $t) { $urls[$p] = $t['url']; }
    $js = "// generated by config admin - do not edit manually\n"
        . "window.SITE_DEFAULT = " . json_encode($default, JSON_UNESCAPED_SLASHES) . ";\n"
        . "window.SITE_TARGETS = " . json_encode($urls, JSON_UNESCAPED_SLASHES | JSON_FORCE_OBJECT) . ";\n";
    file_put_contents($jsFile, $js, LOCK_EX);
}

$error = '';
$msg   = '';
$authed = !empty($_SESSION['auth']);

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (isset($_POST['logout'])) {
        unset($_SESSION['auth']);
        $authed = false;
    } elseif (isset($_POST['login'])) {
        if (hash_equals(adminPass(), (string)$_POST['pass'])) {
            $_SESSION['auth'] = true;
            $authed = true;
        } else {
            $error = '密码错误';
        }
    } elseif ($authed && isset($_POST['save'])) {
        $default = trim((string)($_POST['default_url'] ?? ''));
        if ($default === '') { $default = 'https://pan.quark.cn/s/27b2535c2450'; }
        $targets = array();
        $paths  = (array)($_POST['path'] ?? array());
        $labels = (array)($_POST['label'] ?? array());
        $urls   = (array)($_POST['url'] ?? array());
        foreach ($paths as $i => $p) {
            $p = trim((string)$p);
            $u = trim((string)($urls[$i] ?? ''));
            $l = trim((string)($labels[$i] ?? ''));
            if ($p !== '' && $u !== '') {
                if ($p[0] !== '/') $p = '/' . $p;
                if (substr($p, -1) !== '/') $p .= '/';
                $targets[$p] = array('url' => $u, 'label' => $l);
            }
        }
        saveConf($default, $targets);
        $msg = '已保存并生效';
    } elseif ($authed && isset($_POST['savepass'])) {
        $new = trim((string)($_POST['newpass'] ?? ''));
        if (strlen($new) < 6) {
            $error = '新密码至少6位';
        } else {
            file_put_contents($passFile, "<?php return '" . addslashes($new) . "';\n", LOCK_EX);
            $msg = '密码已修改';
        }
    }
}

$conf = loadConf();
$default = $conf['default'] ?? '';
$targets = $conf['targets'] ?? array();
$hasRows = !empty($targets);
?>
<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>跳转配置后台</title>
<style>
* { box-sizing: border-box; margin: 0; padding: 0; }
body { background: #f4f5f7; font-family: -apple-system, "Segoe UI", "PingFang SC", "Microsoft YaHei", sans-serif; color: #333; }
.wrap { max-width: 760px; margin: 40px auto; padding: 0 16px; }
h1 { font-size: 22px; margin-bottom: 18px; }
.hint { color: #888; font-size: 13px; margin-bottom: 16px; }
.card { background: #fff; border-radius: 12px; padding: 20px; margin-bottom: 14px; box-shadow: 0 2px 12px rgba(0,0,0,0.06); }
label { display: block; font-size: 13px; color: #666; margin-bottom: 8px; }
input[type=text], input[type=password] { width: 100%; padding: 10px 12px; border: 1px solid #ddd; border-radius: 8px; font-size: 14px; margin-bottom: 10px; }
input:focus { outline: none; border-color: #fb7299; }
.row { display: flex; gap: 8px; align-items: center; margin-bottom: 10px; }
.row input { margin-bottom: 0; }
.c-path { flex: 1.4; } .c-label { flex: 1; } .c-url { flex: 2.2; }
.del { border: 0; background: #ffe0e0; color: #d33; width: 34px; height: 36px; border-radius: 8px; cursor: pointer; font-size: 18px; flex: 0 0 34px; }
.row-bar { display: flex; justify-content: space-between; align-items: center; margin-bottom: 12px; }
.btn-primary { background: #fb7299; color: #fff; border: 0; padding: 12px 22px; border-radius: 10px; font-size: 15px; cursor: pointer; }
.btn-secondary { background: #f0f0f0; color: #555; border: 0; padding: 8px 14px; border-radius: 8px; font-size: 13px; cursor: pointer; }
.btn-link { background: none; border: 0; color: #aaa; cursor: pointer; font-size: 12px; margin-top: 4px; }
.ok { background: #e6f7e6; color: #2a7d2a; padding: 10px 12px; border-radius: 8px; font-size: 14px; margin-bottom: 12px; }
.err { background: #fdecea; color: #c03; padding: 10px 12px; border-radius: 8px; font-size: 14px; margin-bottom: 12px; }
.actions { text-align: right; }
.inline { display: flex; gap: 10px; }
.inline input { flex: 1; }
</style>
</head>
<body>
<div class="wrap">
<?php if (!$authed): ?>
  <h1>管理后台登录</h1>
  <?php if ($error) echo '<p class="err">' . htmlspecialchars($error) . '</p>'; ?>
  <form method="post" class="card">
    <label>管理密码</label>
    <input type="password" name="pass" placeholder="请输入管理密码" required>
    <button type="submit" name="login" class="btn-primary">登录</button>
  </form>
<?php else: ?>
  <h1>跳转配置后台</h1>
  <p class="hint">保存后会自动生成 config.js,所有落地页立即按新配置跳转。全局默认地址 + 每个页面可单独指定。</p>
  <?php if ($msg) echo '<p class="ok">' . htmlspecialchars($msg) . '</p>'; ?>
  <?php if ($error) echo '<p class="err">' . htmlspecialchars($error) . '</p>'; ?>
  <form method="post">
    <div class="card">
      <label>全局默认跳转地址(任何页面未单独指定时使用)</label>
      <input type="text" name="default_url" value="<?php echo htmlspecialchars($default, ENT_QUOTES); ?>" placeholder="https://pan.quark.cn/s/xxxxxx">
    </div>
    <div class="card">
      <div class="row-bar">
        <label style="margin:0">页面级跳转规则(路径填写页面访问路径,如 /lian/ 或 /lian/abc/)</label>
        <button type="button" id="addRow" class="btn-secondary">+ 添加一行</button>
      </div>
      <div id="rows">
        <?php foreach ($targets as $p => $t): ?>
        <div class="row">
          <input class="c-path" type="text" name="path[]" value="<?php echo htmlspecialchars($p, ENT_QUOTES); ?>" placeholder="/lian/页面目录/">
          <input class="c-label" type="text" name="label[]" value="<?php echo htmlspecialchars($t['label'] ?? '', ENT_QUOTES); ?>" placeholder="备注(选填)">
          <input class="c-url" type="text" name="url[]" value="<?php echo htmlspecialchars($t['url'] ?? '', ENT_QUOTES); ?>" placeholder="https://pan.quark.cn/s/xxxxxx">
          <button type="button" class="del" onclick="this.parentNode.remove()">&times;</button>
        </div>
        <?php endforeach; ?>
      </div>
    </div>
    <div class="card actions">
      <button type="submit" name="save" class="btn-primary">保存配置并生效</button>
    </div>
  </form>
  <form method="post" class="card inline">
    <label style="margin-bottom:0">修改管理密码:</label>
    <input type="password" name="newpass" placeholder="新密码(至少6位)" minlength="6">
    <button type="submit" name="savepass" class="btn-secondary">修改密码</button>
  </form>
  <form method="post" style="text-align:right">
    <button type="submit" name="logout" class="btn-link">退出登录</button>
  </form>
<?php endif; ?>
</div>
<script>
var addBtn = document.getElementById('addRow');
if (addBtn) addBtn.addEventListener('click', function(){
  var rows = document.getElementById('rows');
  var div = document.createElement('div');
  div.className = 'row';
  div.innerHTML = '<input class="c-path" type="text" name="path[]" placeholder="/lian/页面目录/"/>'
    + '<input class="c-label" type="text" name="label[]" placeholder="备注(选填)"/>'
    + '<input class="c-url" type="text" name="url[]" placeholder="https://pan.quark.cn/s/xxxxxx"/>'
    + '<button type="button" class="del" onclick="this.parentNode.remove()">&times;</button>';
  rows.appendChild(div);
});
</script>
</body>
</html>