// generated by config admin - do not edit manually
window.SITE_DEFAULT = "https://pan.quark.cn/s/27b2535c2450";
window.SITE_TARGETS = {"/lain/":"https://pan.quark.cn/s/27b2535c2450","/lian2/":"https://pan.quark.cn/s/0555b0023715","/lian3/":"https://pan.quark.cn/s/ec94369ea647","/lian4/":"https://pan.quark.cn/s/de9ed8398ec2"};
