// generated by config admin - do not edit manually
window.SITE_DEFAULT = "https://pan.quark.cn/s/27b2535c2450";
window.SITE_TARGETS = {"/lian2/": "https://pan.quark.cn/s/0555b0023715", "/lian3/": "https://pan.quark.cn/s/ec94369ea647", "/lian4/": "https://pan.quark.cn/s/de9ed8398ec2", "/lian/": "https://pan.quark.cn/s/2d7f97658fd5", "/lian5/": "https://pan.quark.cn/s/27b2535c2450", "/lian6/": "https://pan.quark.cn/s/27b2535c2450", "/lian7/": "https://pan.quark.cn/s/27b2535c2450"};
